import type { IBlogCardsInfo } from "../types/global.types";

export const BLOG_CARDS_INFO: IBlogCardsInfo[] = [
  {
    id: 1,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Feb 2",
    readTime: "7 min read",
    title: "Top 5 Benefits of Using Botox for Hyperhidrosis",
    description:
      "Excessive sweating is not just an inconvenience—it can be a major roadblock in both personal confidence and daily activities. For an",
    views: 11,
    comments: 0,
    imgUrl: "/pngs/blogImg1.png",
  },
  {
    id: 2,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 27",
    readTime: "5 min read",
    title: "How Morpheus8 Works for Hyperhidrosis",
    description:
      "Excessive sweating is not just an inconvenience—it can be a major roadblock in both personal confidence and daily activities. For an",
    views: 11,
    comments: 0,
    imgUrl: "/pngs/blogImg2.png",
  },
  {
    id: 3,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 23",
    readTime: "6 min read",
    title: "What are Juvederm Fillers and How Does It Work?",
    description:
      "In the world of aesthetic enhancements, Juvederm fillers have become a household name. Whether you're scrolling through Instagram, wa",
    views: 5,
    comments: 0,
    imgUrl: "/pngs/blogImg3.png",
  },
  {
    id: 4,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 19",
    readTime: "4 min read",
    title: "5 Signs You Might Need PRP Under Eyes Treatment",
    description:
      "The under-eye area is one of the first places to show signs of aging, stress, or fatigue. Dark circles, hollows, and fine lines can leave you looking perpet",
    views: 7,
    comments: 0,
    imgUrl: "/pngs/blogImg4.png",
  },
  {
    id: 5,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 15",
    readTime: "7 min read",
    title: "What Are Bunny Lines and How Can Botox Help?",
    description:
      "You might have noticed some fine lines on either side of your nose when you scrunch it—they're called bunny lines. But what are bunny lines exactly,",
    views: 12,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg5.png",
  },
  {
    id: 6,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 11",
    readTime: "5 min read",
    title: "7 Benefits of Hydro Dermabrasion Facials",
    description:
      "et's cut to the chase: the skincare world is flooded with trends, but few deliver results as consistently as the hydro dermabrasion facial. If you've s",
    views: 11,
    comments: 0,
    imgUrl: "/pngs/blogImg6.png",
  },
  {
    id: 7,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 7",
    readTime: "5 min read",
    title: "What Is Dysport and How Does It Work?",
    description:
      "'What Is Dysport?' might be a question you've asked while exploring cosmetic treatments for smoother, younger-looking skin. Dysport, a popul",
    views: 5,
    comments: 0,
    imgUrl: "/pngs/blogImg7.png",
  },
  {
    id: 8,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 4",
    readTime: "5 min read",
    title: "Radiesse vs Sculptra: Which Filler is Right for You?",
    description:
      "'What Is Dysport?' might be a question you've asked while exploring cosmetic treatments for smoother, younger-looking skin. Dysport, a popul",
    views: 9,
    comments: 0,
    imgUrl: "/pngs/blogImg8.png",
  },
  {
    id: 9,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Jan 2",
    readTime: "5 min read",
    title: "What Is a Back Facial and How Does It Work?",
    description:
      "When it comes to skincare, we often focus solely on our face, forgetting that our back deserves just as much attention. But let's be real: maintainin",
    views: 18,
    comments: 0,
    imgUrl: "/pngs/blogImg9.png",
  },
  {
    id: 10,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 29, 2024",
    readTime: "5 min read",
    title: "Chemical Peel Process Day by Day: What to Expect at Each Stage",
    description:
      "Chemical peels are all the rage these days for anyone wanting to refresh their skin, reduce fine lines, or even address uneven pigmentation. Wheth",
    views: 46,
    comments: 0,
    imgUrl: "/pngs/blogImg10.png",
  },
  {
    id: 11,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 27, 2024",
    readTime: "5 min read",
    title: "How Long Do Dermal Fillers Last? Longevity and Care Tips",
    description:
      "Dermal fillers are a popular cosmetic treatment for those looking to restore volume, smooth out wrinkles, ",
    views: 5,
    comments: 0,
    imgUrl: "/pngs/blogImg11.png",
  },
  {
    id: 12,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 24, 2024",
    readTime: "5 min read",
    title: "5 Reasons to Consider Botox for a Gummy Smile",
    description:
      "Let's talk gummy smiles. They're not exactly a medical problem, but for some, they can be a confidence blocker. A gummy smile happens whe",
    views: 6,
    comments: 0,
    imgUrl: "/pngs/blogImg12.png",
  },
  {
    id: 13,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 23, 2024",
    readTime: "5 min read",
    title: "Why Should You Wait Before Getting a Facial After Botox?",
    description:
      "Botox treatments have become a popular go-to solution for those looking to minimize fine lines and wrinkles, offering a quick and minimall",
    views: 8,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg13.png",
  },
  {
    id: 14,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 22, 2024",
    readTime: "5 min read",
    title: "8 Key Factors That Impact How Long IV Vitamin Therapy Lasts",
    description:
      "IV vitamin therapy has quickly become the go-to wellness trend, offering everything from hydration to enhanced energy. But a common que",
    views: 18,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg14.png",
  },
  {
    id: 15,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 20, 2024",
    readTime: "5 min read",
    title: "What Are Biostimulators? Everything You Need To Know",
    description:
      "In today's world of aesthetic treatments, biostimulators are quickly becoming the ultimate game-changer for achieving natural, long-la",
    views: 23,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg15.png",
  },
  {
    id: 16,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 17, 2024",
    readTime: "6 min read",
    title: "How Long Does Kybella Last and What Is It?",
    description:
      "Kybella has revolutionized the way people address stubborn fat under the chin, offering a non-surgical alternative for contouring and enhanc",
    views: 12,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg16.png",
  },
  {
    id: 17,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 12, 2024",
    readTime: "5 min read",
    title: "What Is an IPL Photofacial? 5 Benefits and Aftercare Tips",
    description:
      "An IPL photofacial is one of the most popular non-invasive cosmetic treatments for improving skin tone and texture. This advanced treatment",
    views: 11,
    comments: 0,
    imgUrl: "/pngs/blogImg17.png",
  },
  {
    id: 18,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Dec 6, 2024",
    readTime: "5 min read",
    title: "How Often Should You Get a Chemical Peel?",
    description:
      "Chemical peels have long been celebrated for their ability to transform the skin, addressing concerns like dullness, fine lines, disco",
    views: 16,
    comments: 0,
    imgUrl: "/pngs/blogImg18.png",
  },
  {
    id: 19,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Nov 29, 2024",
    readTime: "5 min read",
    title: "What Is Morpheus 8?",
    description:
      "If you're looking for an advanced skin treatment that can deliver stunning results without surgery, chances are you've heard about Morpheus 8. This cutting-edge treatment is quickly bec",
    views: 14,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg19.png",
  },
  {
    id: 20,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Nov 25, 2024",
    readTime: "5 min read",
    title: "Laser Hair Removal Zones: Everything You Need to Know",
    description:
      "More and more people are turning to laser hair removal as a reliable way to enjoy silky, hair-free skin. If you're considering this treatment, it's essenti",
    views: 34,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg20.png",
  },
  {
    id: 21,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Nov 20, 2024",
    readTime: "4 min read",
    title: "How to Prepare for Microneedling",
    description:
      "Microneedling has become one of the top choices for skin rejuvenation, offering benefits like improved skin texture, reduced scars, and a youthful glow. However, if you want to get the",
    views: 14,
    comments: 0,
    likeCount: 1,
    imgUrl: "/pngs/blogImg21.png",
  },
  {
    id: 22,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Nov 13, 2024",
    readTime: "5 min read",
    title: "What Desires Can You Have for Facial Service?",
    description:
      "In today’s world, skincare has taken a leading role in self-care, with facial treatment being one of the most popular choices. Whether it's for relax",
    views: 28,
    comments: 0,
    likeCount: 3,
    imgUrl: "/pngs/blogImg22.png",
  },
  {
    id: 23,
    specialistName: "Vahe-Ter Yegishyan FNP-C",
    date: "Nov 14, 2024",
    readTime: "4 min read",
    title: "How Often Should You Get Botox?",
    description:
      "The pursuit of a youthful, radiant complexion is a timeless endeavor. In the modern age, Botox has emerged as a powerful ally in this quest, smoothing out wrinkles and lines, and",
    views: 46,
    comments: 0,
    likeCount: 3,
    imgUrl: "/pngs/blogImg23.png",
  },
];
